### ISSUE TITLE
Segmentation Fault When Running KHARMA 2024.9 with CUDA 

### ISSUE THREAD

**Issue by zzlphysics** [AFD-Illinois/kharma#123]
#### **Description:**
After updating to KHARMA 2024.9, I encountered a segmentation fault when attempting to run the following command:

```bash
./kharma.cuda -i pars/tori_3d/sane.par
```

The error message produced is:

```
[ubuntu-4090:1679525] *** Process received signal ***
[ubuntu-4090:1679525] Signal: Segmentation fault (11)
[ubuntu-4090:1679525] Signal code: Address not mapped (1)
[ubuntu-4090:1679525] Failing at address: (nil)
[ubuntu-4090:1679525] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fe2756b4520]
[ubuntu-4090:1679525] *** End of error message ***
Segmentation fault (core dumped)
```

#### **Environment:**
- KHARMA Version: 2024.9
- CUDA Versions: 11.8.0 or 12.0.0
- OS: Ubuntu 22.04
- GPU: NVIDIA Ada89

#### **Additional Information:**
- The issue does not occur when:
  - Switching `driver/type` from `kharma` to `imex`.
  - Compiling with the `debug` parameter enabled.

  
- Adding the `trace` parameter during compilation yields the following trace leading up to the segmentation fault:
  
  ```
  ......
  Starting CountFlags_fofcflag
  Done
  Starting DomainReduction
  Done
  Starting DomainReduction
  Done
  Starting DomainReduction
  Done
  Starting CountFlags_fflag
  Done
  Starting CountFlags_pflag
  Done
  cycle=0 time=0.0000000000000000e+00 dt=1.0000000000000001e-05 zone-cycles/wsec_step=0.00e+00 wsec_total=2.73e+01 wsec_step=2.88e+01
  Starting PreStepWork
    Starting PreStepWork_Globals
    Done
  Done
  Starting MakeTaskCollection
  [ubuntu-4090:1679525] *** Process received signal ***
  [ubuntu-4090:1679525] Signal: Segmentation fault (11)
  [ubuntu-4090:1679525] Signal code: Address not mapped (1)
  [ubuntu-4090:1679525] Failing at address: (nil)
  [ubuntu-4090:1679525] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fe2756b4520]
  [ubuntu-4090:1679525] *** End of error message ***
  Segmentation fault (core dumped)
  ```

#### **Suspected Problem:**
The segmentation fault seems to occur in the following code block within `kharma/driver/kharma_step.cpp`:

```cpp
if (use_jcon) {
    pmesh->mesh_data.Add("preserve");
    // Above only copies on allocate -- ensure we copy every step
    Copy<MeshData<Real>>({Metadata::Cell}, base.get(), pmesh->mesh_data.Get("preserve").get());
}
```

**Comment by c-prather** [comment]
Thank you for the thorough report!

I think someone saw this while this version was still in `dev` as well, and I never followed up.  I recall they got it working by removing `jcon` from `parthenon/output0/variables`, which looks like it fits very well with what you're seeing.  If you don't need the 4-current output, that might be a nice workaround.

I'll take a look at this today.  It sure feels like a null pointer, but it's very puzzling why it doesn't happen on CPU or in my Nvidia testing.

**Comment by c-prather** [comment]
I still can't reproduce this on any machine I have access to at the moment, but it seems really likely to be a race condition:
1. I ask for the container `"preserve"` to be created
2. Parthenon, through Kokkos, asks Nvidia asynchronously for the relevant `View` space
3. I immediately try to copy the base container contents into the new space, but it's still being allocated, so the `View` is still `nil`

I believe Kokkos switched to asynchronous allocations on CUDA recently, and I suspect the switch has caused us headaches in other places, so it seems logical.
If this is indeed the problem, it should be fixed in `fix/nv-jcon-race`.  Instead of doing the copy while constructing the task list (which is also a bad example, as functions should nearly always be added to the list instead of run directly), we now add the copy as its own task at the very front of the list.  I also cut down on the number of variables we preserve, producing a small (~1%) speedup.
If this doesn't fix things, my local Rome/A100 machine should be back up next week, and I'll try to reproduce it there next Monday.

**Comment by zzlphysics** [comment]
Thank you for your prompt response!

1. I appreciate your insights on the potential race condition with asynchronous allocations.
2. I tried disabling asynchronous memory allocations with `-DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF`, but the segmentation fault persisted.
3. The issue is resolved in the `fix/nv-jcon-race` branch. The updated approach of adding the copy as a task works perfectly.

Thanks again for the quick fix!

**Comment by c-prather** [comment]
Great!  I'll merge the fix and mark resolved then.

Interesting that disabling `CUDA_MALLOC_ASYNC` also doesn't fix it.  The only other place I could imagine a race condition is in Parthenon: the task list is created in a separate thread from where tasks are executed (it was the first step toward introducing multi-threading in the future).  The two threads aren't supposed to run at the same time on the CPU, but they may not share the same queue on the GPU.  Still weird that two requests from the same thread manage to collide...

If that wild theory is true it speaks to why I couldn't replicate the problem, since I normally run on machines with comparatively slow CPU cores (ARM, older x86), which may not run ahead as far on CPU compared to the GPU queues.

Anyway I think the moral here is to stick to having `MakeTaskCollection` do as little as possible besides what it's named to do!
